/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogTerraplanagemOuTerraplenagemRouteImport } from './routes/blog.terraplanagem-ou-terraplenagem'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppEntrarRouteImport } from './routes/app.entrar'
import { Route as AdminRentabilidadeRouteImport } from './routes/admin.rentabilidade'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminManutencaoRouteImport } from './routes/admin.manutencao'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminGerencialRouteImport } from './routes/admin.gerencial'
import { Route as AdminDieselRouteImport } from './routes/admin.diesel'
import { Route as AdminCustoHoraRouteImport } from './routes/admin.custo-hora'
import { Route as AppOrdensIndexRouteImport } from './routes/app.ordens.index'
import { Route as AppApontamentoIndexRouteImport } from './routes/app.apontamento.index'
import { Route as AdminOrdensIndexRouteImport } from './routes/admin.ordens.index'
import { Route as AdminOrcamentosIndexRouteImport } from './routes/admin.orcamentos.index'
import { Route as AdminOperadoresIndexRouteImport } from './routes/admin.operadores.index'
import { Route as AdminFinanceiroIndexRouteImport } from './routes/admin.financeiro.index'
import { Route as AdminFaturamentoIndexRouteImport } from './routes/admin.faturamento.index'
import { Route as AdminEquipamentosIndexRouteImport } from './routes/admin.equipamentos.index'
import { Route as AdminComprovantesIndexRouteImport } from './routes/admin.comprovantes.index'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AppOrdensOrdemIdRouteImport } from './routes/app.ordens.$ordemId'
import { Route as AppApontamentoNovoRouteImport } from './routes/app.apontamento.novo'
import { Route as AppApontamentoApontamentoIdRouteImport } from './routes/app.apontamento.$apontamentoId'
import { Route as AdminOrdensNovaRouteImport } from './routes/admin.ordens.nova'
import { Route as AdminOrdensOrdemIdRouteImport } from './routes/admin.ordens.$ordemId'
import { Route as AdminOrcamentosOrcamentoIdRouteImport } from './routes/admin.orcamentos.$orcamentoId'
import { Route as AdminOperadoresOperadorIdRouteImport } from './routes/admin.operadores.$operadorId'
import { Route as AdminIaChatbotRouteImport } from './routes/admin.ia.chatbot'
import { Route as AdminFaturamentoFaturamentoIdRouteImport } from './routes/admin.faturamento.$faturamentoId'
import { Route as AdminEquipamentosNovoRouteImport } from './routes/admin.equipamentos.novo'
import { Route as AdminEquipamentosEquipamentoIdRouteImport } from './routes/admin.equipamentos.$equipamentoId'
import { Route as AdminCustoHoraNovoRouteImport } from './routes/admin.custo-hora.novo'
import { Route as AdminComprovantesComprovanteIdRouteImport } from './routes/admin.comprovantes.$comprovanteId'
import { Route as AdminClientesNovoRouteImport } from './routes/admin.clientes.novo'
import { Route as AdminClientesClienteIdRouteImport } from './routes/admin.clientes.$clienteId'
import { Route as AdminFinanceiroContasPagarNovoRouteImport } from './routes/admin.financeiro.contas-pagar.novo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogTerraplanagemOuTerraplenagemRoute =
  BlogTerraplanagemOuTerraplenagemRouteImport.update({
    id: '/blog/terraplanagem-ou-terraplenagem',
    path: '/blog/terraplanagem-ou-terraplenagem',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrarRoute = AppEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => AppRoute,
} as any)
const AdminRentabilidadeRoute = AdminRentabilidadeRouteImport.update({
  id: '/rentabilidade',
  path: '/rentabilidade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManutencaoRoute = AdminManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGerencialRoute = AdminGerencialRouteImport.update({
  id: '/gerencial',
  path: '/gerencial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDieselRoute = AdminDieselRouteImport.update({
  id: '/diesel',
  path: '/diesel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustoHoraRoute = AdminCustoHoraRouteImport.update({
  id: '/custo-hora',
  path: '/custo-hora',
  getParentRoute: () => AdminRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRoute,
} as any)
const AppApontamentoIndexRoute = AppApontamentoIndexRouteImport.update({
  id: '/apontamento/',
  path: '/apontamento/',
  getParentRoute: () => AppRoute,
} as any)
const AdminOrdensIndexRoute = AdminOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosIndexRoute = AdminOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperadoresIndexRoute = AdminOperadoresIndexRouteImport.update({
  id: '/operadores/',
  path: '/operadores/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroIndexRoute = AdminFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturamentoIndexRoute = AdminFaturamentoIndexRouteImport.update({
  id: '/faturamento/',
  path: '/faturamento/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipamentosIndexRoute = AdminEquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComprovantesIndexRoute = AdminComprovantesIndexRouteImport.update({
  id: '/comprovantes/',
  path: '/comprovantes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AppOrdensOrdemIdRoute = AppOrdensOrdemIdRouteImport.update({
  id: '/ordens/$ordemId',
  path: '/ordens/$ordemId',
  getParentRoute: () => AppRoute,
} as any)
const AppApontamentoNovoRoute = AppApontamentoNovoRouteImport.update({
  id: '/apontamento/novo',
  path: '/apontamento/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppApontamentoApontamentoIdRoute =
  AppApontamentoApontamentoIdRouteImport.update({
    id: '/apontamento/$apontamentoId',
    path: '/apontamento/$apontamentoId',
    getParentRoute: () => AppRoute,
  } as any)
const AdminOrdensNovaRoute = AdminOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdensOrdemIdRoute = AdminOrdensOrdemIdRouteImport.update({
  id: '/ordens/$ordemId',
  path: '/ordens/$ordemId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosOrcamentoIdRoute =
  AdminOrcamentosOrcamentoIdRouteImport.update({
    id: '/orcamentos/$orcamentoId',
    path: '/orcamentos/$orcamentoId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOperadoresOperadorIdRoute =
  AdminOperadoresOperadorIdRouteImport.update({
    id: '/operadores/$operadorId',
    path: '/operadores/$operadorId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIaChatbotRoute = AdminIaChatbotRouteImport.update({
  id: '/ia/chatbot',
  path: '/ia/chatbot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaturamentoFaturamentoIdRoute =
  AdminFaturamentoFaturamentoIdRouteImport.update({
    id: '/faturamento/$faturamentoId',
    path: '/faturamento/$faturamentoId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEquipamentosNovoRoute = AdminEquipamentosNovoRouteImport.update({
  id: '/equipamentos/novo',
  path: '/equipamentos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipamentosEquipamentoIdRoute =
  AdminEquipamentosEquipamentoIdRouteImport.update({
    id: '/equipamentos/$equipamentoId',
    path: '/equipamentos/$equipamentoId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustoHoraNovoRoute = AdminCustoHoraNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminCustoHoraRoute,
} as any)
const AdminComprovantesComprovanteIdRoute =
  AdminComprovantesComprovanteIdRouteImport.update({
    id: '/comprovantes/$comprovanteId',
    path: '/comprovantes/$comprovanteId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminClientesNovoRoute = AdminClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesClienteIdRoute = AdminClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroContasPagarNovoRoute =
  AdminFinanceiroContasPagarNovoRouteImport.update({
    id: '/financeiro/contas-pagar/novo',
    path: '/financeiro/contas-pagar/novo',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/custo-hora': typeof AdminCustoHoraRouteWithChildren
  '/admin/diesel': typeof AdminDieselRoute
  '/admin/gerencial': typeof AdminGerencialRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/manutencao': typeof AdminManutencaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/rentabilidade': typeof AdminRentabilidadeRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/terraplanagem-ou-terraplenagem': typeof BlogTerraplanagemOuTerraplenagemRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/comprovantes/$comprovanteId': typeof AdminComprovantesComprovanteIdRoute
  '/admin/custo-hora/novo': typeof AdminCustoHoraNovoRoute
  '/admin/equipamentos/$equipamentoId': typeof AdminEquipamentosEquipamentoIdRoute
  '/admin/equipamentos/novo': typeof AdminEquipamentosNovoRoute
  '/admin/faturamento/$faturamentoId': typeof AdminFaturamentoFaturamentoIdRoute
  '/admin/ia/chatbot': typeof AdminIaChatbotRoute
  '/admin/operadores/$operadorId': typeof AdminOperadoresOperadorIdRoute
  '/admin/orcamentos/$orcamentoId': typeof AdminOrcamentosOrcamentoIdRoute
  '/admin/ordens/$ordemId': typeof AdminOrdensOrdemIdRoute
  '/admin/ordens/nova': typeof AdminOrdensNovaRoute
  '/app/apontamento/$apontamentoId': typeof AppApontamentoApontamentoIdRoute
  '/app/apontamento/novo': typeof AppApontamentoNovoRoute
  '/app/ordens/$ordemId': typeof AppOrdensOrdemIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/comprovantes/': typeof AdminComprovantesIndexRoute
  '/admin/equipamentos/': typeof AdminEquipamentosIndexRoute
  '/admin/faturamento/': typeof AdminFaturamentoIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/operadores/': typeof AdminOperadoresIndexRoute
  '/admin/orcamentos/': typeof AdminOrcamentosIndexRoute
  '/admin/ordens/': typeof AdminOrdensIndexRoute
  '/app/apontamento/': typeof AppApontamentoIndexRoute
  '/app/ordens/': typeof AppOrdensIndexRoute
  '/admin/financeiro/contas-pagar/novo': typeof AdminFinanceiroContasPagarNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/custo-hora': typeof AdminCustoHoraRouteWithChildren
  '/admin/diesel': typeof AdminDieselRoute
  '/admin/gerencial': typeof AdminGerencialRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/manutencao': typeof AdminManutencaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/rentabilidade': typeof AdminRentabilidadeRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/terraplanagem-ou-terraplenagem': typeof BlogTerraplanagemOuTerraplenagemRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/comprovantes/$comprovanteId': typeof AdminComprovantesComprovanteIdRoute
  '/admin/custo-hora/novo': typeof AdminCustoHoraNovoRoute
  '/admin/equipamentos/$equipamentoId': typeof AdminEquipamentosEquipamentoIdRoute
  '/admin/equipamentos/novo': typeof AdminEquipamentosNovoRoute
  '/admin/faturamento/$faturamentoId': typeof AdminFaturamentoFaturamentoIdRoute
  '/admin/ia/chatbot': typeof AdminIaChatbotRoute
  '/admin/operadores/$operadorId': typeof AdminOperadoresOperadorIdRoute
  '/admin/orcamentos/$orcamentoId': typeof AdminOrcamentosOrcamentoIdRoute
  '/admin/ordens/$ordemId': typeof AdminOrdensOrdemIdRoute
  '/admin/ordens/nova': typeof AdminOrdensNovaRoute
  '/app/apontamento/$apontamentoId': typeof AppApontamentoApontamentoIdRoute
  '/app/apontamento/novo': typeof AppApontamentoNovoRoute
  '/app/ordens/$ordemId': typeof AppOrdensOrdemIdRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/comprovantes': typeof AdminComprovantesIndexRoute
  '/admin/equipamentos': typeof AdminEquipamentosIndexRoute
  '/admin/faturamento': typeof AdminFaturamentoIndexRoute
  '/admin/financeiro': typeof AdminFinanceiroIndexRoute
  '/admin/operadores': typeof AdminOperadoresIndexRoute
  '/admin/orcamentos': typeof AdminOrcamentosIndexRoute
  '/admin/ordens': typeof AdminOrdensIndexRoute
  '/app/apontamento': typeof AppApontamentoIndexRoute
  '/app/ordens': typeof AppOrdensIndexRoute
  '/admin/financeiro/contas-pagar/novo': typeof AdminFinanceiroContasPagarNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/custo-hora': typeof AdminCustoHoraRouteWithChildren
  '/admin/diesel': typeof AdminDieselRoute
  '/admin/gerencial': typeof AdminGerencialRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/manutencao': typeof AdminManutencaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/rentabilidade': typeof AdminRentabilidadeRoute
  '/app/entrar': typeof AppEntrarRoute
  '/app/perfil': typeof AppPerfilRoute
  '/blog/terraplanagem-ou-terraplenagem': typeof BlogTerraplanagemOuTerraplenagemRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/clientes/$clienteId': typeof AdminClientesClienteIdRoute
  '/admin/clientes/novo': typeof AdminClientesNovoRoute
  '/admin/comprovantes/$comprovanteId': typeof AdminComprovantesComprovanteIdRoute
  '/admin/custo-hora/novo': typeof AdminCustoHoraNovoRoute
  '/admin/equipamentos/$equipamentoId': typeof AdminEquipamentosEquipamentoIdRoute
  '/admin/equipamentos/novo': typeof AdminEquipamentosNovoRoute
  '/admin/faturamento/$faturamentoId': typeof AdminFaturamentoFaturamentoIdRoute
  '/admin/ia/chatbot': typeof AdminIaChatbotRoute
  '/admin/operadores/$operadorId': typeof AdminOperadoresOperadorIdRoute
  '/admin/orcamentos/$orcamentoId': typeof AdminOrcamentosOrcamentoIdRoute
  '/admin/ordens/$ordemId': typeof AdminOrdensOrdemIdRoute
  '/admin/ordens/nova': typeof AdminOrdensNovaRoute
  '/app/apontamento/$apontamentoId': typeof AppApontamentoApontamentoIdRoute
  '/app/apontamento/novo': typeof AppApontamentoNovoRoute
  '/app/ordens/$ordemId': typeof AppOrdensOrdemIdRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/comprovantes/': typeof AdminComprovantesIndexRoute
  '/admin/equipamentos/': typeof AdminEquipamentosIndexRoute
  '/admin/faturamento/': typeof AdminFaturamentoIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
  '/admin/operadores/': typeof AdminOperadoresIndexRoute
  '/admin/orcamentos/': typeof AdminOrcamentosIndexRoute
  '/admin/ordens/': typeof AdminOrdensIndexRoute
  '/app/apontamento/': typeof AppApontamentoIndexRoute
  '/app/ordens/': typeof AppOrdensIndexRoute
  '/admin/financeiro/contas-pagar/novo': typeof AdminFinanceiroContasPagarNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/custo-hora'
    | '/admin/diesel'
    | '/admin/gerencial'
    | '/admin/integracoes'
    | '/admin/manutencao'
    | '/admin/precos'
    | '/admin/rentabilidade'
    | '/app/entrar'
    | '/app/perfil'
    | '/blog/terraplanagem-ou-terraplenagem'
    | '/admin/'
    | '/app/'
    | '/admin/clientes/$clienteId'
    | '/admin/clientes/novo'
    | '/admin/comprovantes/$comprovanteId'
    | '/admin/custo-hora/novo'
    | '/admin/equipamentos/$equipamentoId'
    | '/admin/equipamentos/novo'
    | '/admin/faturamento/$faturamentoId'
    | '/admin/ia/chatbot'
    | '/admin/operadores/$operadorId'
    | '/admin/orcamentos/$orcamentoId'
    | '/admin/ordens/$ordemId'
    | '/admin/ordens/nova'
    | '/app/apontamento/$apontamentoId'
    | '/app/apontamento/novo'
    | '/app/ordens/$ordemId'
    | '/admin/clientes/'
    | '/admin/comprovantes/'
    | '/admin/equipamentos/'
    | '/admin/faturamento/'
    | '/admin/financeiro/'
    | '/admin/operadores/'
    | '/admin/orcamentos/'
    | '/admin/ordens/'
    | '/app/apontamento/'
    | '/app/ordens/'
    | '/admin/financeiro/contas-pagar/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/custo-hora'
    | '/admin/diesel'
    | '/admin/gerencial'
    | '/admin/integracoes'
    | '/admin/manutencao'
    | '/admin/precos'
    | '/admin/rentabilidade'
    | '/app/entrar'
    | '/app/perfil'
    | '/blog/terraplanagem-ou-terraplenagem'
    | '/admin'
    | '/app'
    | '/admin/clientes/$clienteId'
    | '/admin/clientes/novo'
    | '/admin/comprovantes/$comprovanteId'
    | '/admin/custo-hora/novo'
    | '/admin/equipamentos/$equipamentoId'
    | '/admin/equipamentos/novo'
    | '/admin/faturamento/$faturamentoId'
    | '/admin/ia/chatbot'
    | '/admin/operadores/$operadorId'
    | '/admin/orcamentos/$orcamentoId'
    | '/admin/ordens/$ordemId'
    | '/admin/ordens/nova'
    | '/app/apontamento/$apontamentoId'
    | '/app/apontamento/novo'
    | '/app/ordens/$ordemId'
    | '/admin/clientes'
    | '/admin/comprovantes'
    | '/admin/equipamentos'
    | '/admin/faturamento'
    | '/admin/financeiro'
    | '/admin/operadores'
    | '/admin/orcamentos'
    | '/admin/ordens'
    | '/app/apontamento'
    | '/app/ordens'
    | '/admin/financeiro/contas-pagar/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/admin/custo-hora'
    | '/admin/diesel'
    | '/admin/gerencial'
    | '/admin/integracoes'
    | '/admin/manutencao'
    | '/admin/precos'
    | '/admin/rentabilidade'
    | '/app/entrar'
    | '/app/perfil'
    | '/blog/terraplanagem-ou-terraplenagem'
    | '/admin/'
    | '/app/'
    | '/admin/clientes/$clienteId'
    | '/admin/clientes/novo'
    | '/admin/comprovantes/$comprovanteId'
    | '/admin/custo-hora/novo'
    | '/admin/equipamentos/$equipamentoId'
    | '/admin/equipamentos/novo'
    | '/admin/faturamento/$faturamentoId'
    | '/admin/ia/chatbot'
    | '/admin/operadores/$operadorId'
    | '/admin/orcamentos/$orcamentoId'
    | '/admin/ordens/$ordemId'
    | '/admin/ordens/nova'
    | '/app/apontamento/$apontamentoId'
    | '/app/apontamento/novo'
    | '/app/ordens/$ordemId'
    | '/admin/clientes/'
    | '/admin/comprovantes/'
    | '/admin/equipamentos/'
    | '/admin/faturamento/'
    | '/admin/financeiro/'
    | '/admin/operadores/'
    | '/admin/orcamentos/'
    | '/admin/ordens/'
    | '/app/apontamento/'
    | '/app/ordens/'
    | '/admin/financeiro/contas-pagar/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogTerraplanagemOuTerraplenagemRoute: typeof BlogTerraplanagemOuTerraplenagemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/terraplanagem-ou-terraplenagem': {
      id: '/blog/terraplanagem-ou-terraplenagem'
      path: '/blog/terraplanagem-ou-terraplenagem'
      fullPath: '/blog/terraplanagem-ou-terraplenagem'
      preLoaderRoute: typeof BlogTerraplanagemOuTerraplenagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entrar': {
      id: '/app/entrar'
      path: '/entrar'
      fullPath: '/app/entrar'
      preLoaderRoute: typeof AppEntrarRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/rentabilidade': {
      id: '/admin/rentabilidade'
      path: '/rentabilidade'
      fullPath: '/admin/rentabilidade'
      preLoaderRoute: typeof AdminRentabilidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manutencao': {
      id: '/admin/manutencao'
      path: '/manutencao'
      fullPath: '/admin/manutencao'
      preLoaderRoute: typeof AdminManutencaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gerencial': {
      id: '/admin/gerencial'
      path: '/gerencial'
      fullPath: '/admin/gerencial'
      preLoaderRoute: typeof AdminGerencialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diesel': {
      id: '/admin/diesel'
      path: '/diesel'
      fullPath: '/admin/diesel'
      preLoaderRoute: typeof AdminDieselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custo-hora': {
      id: '/admin/custo-hora'
      path: '/custo-hora'
      fullPath: '/admin/custo-hora'
      preLoaderRoute: typeof AdminCustoHoraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/ordens/': {
      id: '/app/ordens/'
      path: '/ordens'
      fullPath: '/app/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apontamento/': {
      id: '/app/apontamento/'
      path: '/apontamento'
      fullPath: '/app/apontamento/'
      preLoaderRoute: typeof AppApontamentoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/ordens/': {
      id: '/admin/ordens/'
      path: '/ordens'
      fullPath: '/admin/ordens/'
      preLoaderRoute: typeof AdminOrdensIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos/': {
      id: '/admin/orcamentos/'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos/'
      preLoaderRoute: typeof AdminOrcamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operadores/': {
      id: '/admin/operadores/'
      path: '/operadores'
      fullPath: '/admin/operadores/'
      preLoaderRoute: typeof AdminOperadoresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/': {
      id: '/admin/financeiro/'
      path: '/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminFinanceiroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturamento/': {
      id: '/admin/faturamento/'
      path: '/faturamento'
      fullPath: '/admin/faturamento/'
      preLoaderRoute: typeof AdminFaturamentoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipamentos/': {
      id: '/admin/equipamentos/'
      path: '/equipamentos'
      fullPath: '/admin/equipamentos/'
      preLoaderRoute: typeof AdminEquipamentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comprovantes/': {
      id: '/admin/comprovantes/'
      path: '/comprovantes'
      fullPath: '/admin/comprovantes/'
      preLoaderRoute: typeof AdminComprovantesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/ordens/$ordemId': {
      id: '/app/ordens/$ordemId'
      path: '/ordens/$ordemId'
      fullPath: '/app/ordens/$ordemId'
      preLoaderRoute: typeof AppOrdensOrdemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apontamento/novo': {
      id: '/app/apontamento/novo'
      path: '/apontamento/novo'
      fullPath: '/app/apontamento/novo'
      preLoaderRoute: typeof AppApontamentoNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apontamento/$apontamentoId': {
      id: '/app/apontamento/$apontamentoId'
      path: '/apontamento/$apontamentoId'
      fullPath: '/app/apontamento/$apontamentoId'
      preLoaderRoute: typeof AppApontamentoApontamentoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/ordens/nova': {
      id: '/admin/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/admin/ordens/nova'
      preLoaderRoute: typeof AdminOrdensNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ordens/$ordemId': {
      id: '/admin/ordens/$ordemId'
      path: '/ordens/$ordemId'
      fullPath: '/admin/ordens/$ordemId'
      preLoaderRoute: typeof AdminOrdensOrdemIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos/$orcamentoId': {
      id: '/admin/orcamentos/$orcamentoId'
      path: '/orcamentos/$orcamentoId'
      fullPath: '/admin/orcamentos/$orcamentoId'
      preLoaderRoute: typeof AdminOrcamentosOrcamentoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operadores/$operadorId': {
      id: '/admin/operadores/$operadorId'
      path: '/operadores/$operadorId'
      fullPath: '/admin/operadores/$operadorId'
      preLoaderRoute: typeof AdminOperadoresOperadorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia/chatbot': {
      id: '/admin/ia/chatbot'
      path: '/ia/chatbot'
      fullPath: '/admin/ia/chatbot'
      preLoaderRoute: typeof AdminIaChatbotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faturamento/$faturamentoId': {
      id: '/admin/faturamento/$faturamentoId'
      path: '/faturamento/$faturamentoId'
      fullPath: '/admin/faturamento/$faturamentoId'
      preLoaderRoute: typeof AdminFaturamentoFaturamentoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipamentos/novo': {
      id: '/admin/equipamentos/novo'
      path: '/equipamentos/novo'
      fullPath: '/admin/equipamentos/novo'
      preLoaderRoute: typeof AdminEquipamentosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipamentos/$equipamentoId': {
      id: '/admin/equipamentos/$equipamentoId'
      path: '/equipamentos/$equipamentoId'
      fullPath: '/admin/equipamentos/$equipamentoId'
      preLoaderRoute: typeof AdminEquipamentosEquipamentoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/custo-hora/novo': {
      id: '/admin/custo-hora/novo'
      path: '/novo'
      fullPath: '/admin/custo-hora/novo'
      preLoaderRoute: typeof AdminCustoHoraNovoRouteImport
      parentRoute: typeof AdminCustoHoraRoute
    }
    '/admin/comprovantes/$comprovanteId': {
      id: '/admin/comprovantes/$comprovanteId'
      path: '/comprovantes/$comprovanteId'
      fullPath: '/admin/comprovantes/$comprovanteId'
      preLoaderRoute: typeof AdminComprovantesComprovanteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/novo': {
      id: '/admin/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/admin/clientes/novo'
      preLoaderRoute: typeof AdminClientesNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$clienteId': {
      id: '/admin/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/admin/clientes/$clienteId'
      preLoaderRoute: typeof AdminClientesClienteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/contas-pagar/novo': {
      id: '/admin/financeiro/contas-pagar/novo'
      path: '/financeiro/contas-pagar/novo'
      fullPath: '/admin/financeiro/contas-pagar/novo'
      preLoaderRoute: typeof AdminFinanceiroContasPagarNovoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminCustoHoraRouteChildren {
  AdminCustoHoraNovoRoute: typeof AdminCustoHoraNovoRoute
}

const AdminCustoHoraRouteChildren: AdminCustoHoraRouteChildren = {
  AdminCustoHoraNovoRoute: AdminCustoHoraNovoRoute,
}

const AdminCustoHoraRouteWithChildren = AdminCustoHoraRoute._addFileChildren(
  AdminCustoHoraRouteChildren,
)

interface AdminRouteChildren {
  AdminCustoHoraRoute: typeof AdminCustoHoraRouteWithChildren
  AdminDieselRoute: typeof AdminDieselRoute
  AdminGerencialRoute: typeof AdminGerencialRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminManutencaoRoute: typeof AdminManutencaoRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminRentabilidadeRoute: typeof AdminRentabilidadeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesClienteIdRoute: typeof AdminClientesClienteIdRoute
  AdminClientesNovoRoute: typeof AdminClientesNovoRoute
  AdminComprovantesComprovanteIdRoute: typeof AdminComprovantesComprovanteIdRoute
  AdminEquipamentosEquipamentoIdRoute: typeof AdminEquipamentosEquipamentoIdRoute
  AdminEquipamentosNovoRoute: typeof AdminEquipamentosNovoRoute
  AdminFaturamentoFaturamentoIdRoute: typeof AdminFaturamentoFaturamentoIdRoute
  AdminIaChatbotRoute: typeof AdminIaChatbotRoute
  AdminOperadoresOperadorIdRoute: typeof AdminOperadoresOperadorIdRoute
  AdminOrcamentosOrcamentoIdRoute: typeof AdminOrcamentosOrcamentoIdRoute
  AdminOrdensOrdemIdRoute: typeof AdminOrdensOrdemIdRoute
  AdminOrdensNovaRoute: typeof AdminOrdensNovaRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminComprovantesIndexRoute: typeof AdminComprovantesIndexRoute
  AdminEquipamentosIndexRoute: typeof AdminEquipamentosIndexRoute
  AdminFaturamentoIndexRoute: typeof AdminFaturamentoIndexRoute
  AdminFinanceiroIndexRoute: typeof AdminFinanceiroIndexRoute
  AdminOperadoresIndexRoute: typeof AdminOperadoresIndexRoute
  AdminOrcamentosIndexRoute: typeof AdminOrcamentosIndexRoute
  AdminOrdensIndexRoute: typeof AdminOrdensIndexRoute
  AdminFinanceiroContasPagarNovoRoute: typeof AdminFinanceiroContasPagarNovoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustoHoraRoute: AdminCustoHoraRouteWithChildren,
  AdminDieselRoute: AdminDieselRoute,
  AdminGerencialRoute: AdminGerencialRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminManutencaoRoute: AdminManutencaoRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminRentabilidadeRoute: AdminRentabilidadeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesClienteIdRoute: AdminClientesClienteIdRoute,
  AdminClientesNovoRoute: AdminClientesNovoRoute,
  AdminComprovantesComprovanteIdRoute: AdminComprovantesComprovanteIdRoute,
  AdminEquipamentosEquipamentoIdRoute: AdminEquipamentosEquipamentoIdRoute,
  AdminEquipamentosNovoRoute: AdminEquipamentosNovoRoute,
  AdminFaturamentoFaturamentoIdRoute: AdminFaturamentoFaturamentoIdRoute,
  AdminIaChatbotRoute: AdminIaChatbotRoute,
  AdminOperadoresOperadorIdRoute: AdminOperadoresOperadorIdRoute,
  AdminOrcamentosOrcamentoIdRoute: AdminOrcamentosOrcamentoIdRoute,
  AdminOrdensOrdemIdRoute: AdminOrdensOrdemIdRoute,
  AdminOrdensNovaRoute: AdminOrdensNovaRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminComprovantesIndexRoute: AdminComprovantesIndexRoute,
  AdminEquipamentosIndexRoute: AdminEquipamentosIndexRoute,
  AdminFaturamentoIndexRoute: AdminFaturamentoIndexRoute,
  AdminFinanceiroIndexRoute: AdminFinanceiroIndexRoute,
  AdminOperadoresIndexRoute: AdminOperadoresIndexRoute,
  AdminOrcamentosIndexRoute: AdminOrcamentosIndexRoute,
  AdminOrdensIndexRoute: AdminOrdensIndexRoute,
  AdminFinanceiroContasPagarNovoRoute: AdminFinanceiroContasPagarNovoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppEntrarRoute: typeof AppEntrarRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppApontamentoApontamentoIdRoute: typeof AppApontamentoApontamentoIdRoute
  AppApontamentoNovoRoute: typeof AppApontamentoNovoRoute
  AppOrdensOrdemIdRoute: typeof AppOrdensOrdemIdRoute
  AppApontamentoIndexRoute: typeof AppApontamentoIndexRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEntrarRoute: AppEntrarRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppApontamentoApontamentoIdRoute: AppApontamentoApontamentoIdRoute,
  AppApontamentoNovoRoute: AppApontamentoNovoRoute,
  AppOrdensOrdemIdRoute: AppOrdensOrdemIdRoute,
  AppApontamentoIndexRoute: AppApontamentoIndexRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogTerraplanagemOuTerraplenagemRoute: BlogTerraplanagemOuTerraplenagemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
